In [3]:
#!pip install kaggle
import kaggle

Requirement already satisfied: kaggle in c:\users\huawei\anaconda3\lib\site-packages (1.7.4.2)
Requirement already satisfied: bleach in c:\users\huawei\anaconda3\lib\site-packages (from kaggle) (4.1.0)
Requirement already satisfied: certifi>=14.05.14 in c:\users\huawei\anaconda3\lib\site-packages (from kaggle) (2025.1.31)
Requirement already satisfied: charset-normalizer in c:\users\huawei\anaconda3\lib\site-packages (from kaggle) (2.0.4)
Requirement already satisfied: idna in c:\users\huawei\anaconda3\lib\site-packages (from kaggle) (3.4)
Requirement already satisfied: protobuf in c:\users\huawei\anaconda3\lib\site-packages (from kaggle) (6.30.2)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\huawei\anaconda3\lib\site-packages (from kaggle) (2.8.2)
Requirement already satisfied: python-slugify in c:\users\huawei\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: requests in c:\users\huawei\anaconda3\lib\site-packages (from kaggle) (2.31.0)
Requirement already satisfied: setuptools>=21.0.0 in c:\users\huawei\anaconda3\lib\site-packages (from kaggle) (68.0.0)
Requirement already satisfied: six>=1.10 in c:\users\huawei\anaconda3\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: text-unidecode in c:\users\huawei\anaconda3\lib\site-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in c:\users\huawei\anaconda3\lib\site-packages (from kaggle) (4.65.0)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\huawei\anaconda3\lib\site-packages (from kaggle) (1.26.16)
Requirement already satisfied: webencodings in c:\users\huawei\anaconda3\lib\site-packages (from kaggle) (0.5.1)
Requirement already satisfied: packaging in c:\users\huawei\anaconda3\lib\site-packages (from bleach->kaggle) (23.1)
Requirement already satisfied: colorama in c:\users\huawei\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)
Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv: Skipping, found more recently modified local copy (use --force to force download)

In [4]:
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv: Skipping, found more recently modified local copy (use --force to force download)

In [5]:
!kaggle --version

Kaggle API 1.7.4.2

In [7]:
!kaggle datasets download -d ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv: Skipping, found more recently modified local copy (use --force to force download)

In [9]:
!kaggle datasets download -d ankitbansal06/retail-orders --force

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading retail-orders.zip to C:\Users\HUAWEI\Documents\Python + SQL

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:00<00:00, 79.7MB/s]

In [17]:
import zipfile
zip_ref = zipfile.ZipFile('retail-orders.zip')
zip_ref.extractall()
zip_ref.close()

In [19]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\huawei\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\huawei\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\huawei\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\huawei\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\huawei\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\huawei\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [39]:
import pandas as pd
df= pd.read_csv('orders.csv',na_values=['Not Available','unknown'])
df.head(5)
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [41]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [42]:
df.head(5)

,Order_Id,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Product_Id,cost_price,List_Price,Quantity,Discount_Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [43]:
df.columns = df.columns.astype(str).str.lower()

In [44]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [45]:
df['discount']=df['list_price']*df['discount_percent']*0.01

In [46]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2

In [47]:
df['sales_price']=df['list_price']-df['discount']

In [48]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sales_price
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8

In [81]:
df['profit']=df['sales_price']-df['cost_price']
df

KeyError: 'cost_price'

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sales_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [51]:
df.dtypes

order_id              int64
order_date           object
ship_mode            object
segment              object
country              object
city                 object
state                object
postal_code           int64
region               object
category             object
sub_category         object
product_id           object
cost_price            int64
list_price            int64
quantity              int64
discount_percent      int64
discount            float64
sales_price         float64
profit              float64
dtype: object

In [53]:
df['order_date']=pd.to_datetime(df['order_date'],format="%Y-%m-%d")

In [54]:
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sales_price                float64
profit                     float64
dtype: object

In [63]:
df.drop(columns=['list_price','cost_price','discount_percent'],inplace=True,errors='ignore')

In [64]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sales_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [65]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\huawei\anaconda3\lib\site-packages (1.4.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\huawei\anaconda3\lib\site-packages (from sqlalchemy) (2.0.1)

In [67]:
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\huawei\anaconda3\lib\site-packages (1.1.1)

In [68]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\huawei\anaconda3\lib\site-packages (1.4.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\huawei\anaconda3\lib\site-packages (from sqlalchemy) (2.0.1)

In [69]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Obtaining dependency information for mysql-connector-python from https://files.pythonhosted.org/packages/e2/18/42761250be6ad43a23edb7af85b9720ba8aa1a652036ab4854724d21f628/mysql_connector_python-9.2.0-cp311-cp311-win_amd64.whl.metadata
  Downloading mysql_connector_python-9.2.0-cp311-cp311-win_amd64.whl.metadata (6.2 kB)
Downloading mysql_connector_python-9.2.0-cp311-cp311-win_amd64.whl (16.1 MB)
   ---------------------------------------- 0.0/16.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.1 MB ? eta -:--:--
   ---------------------------------------- 0.1/16.1 MB 2.1 MB/s eta 0:00:08
    --------------------------------------- 0.4/16.1 MB 4.1 MB/s eta 0:00:04
   - -------------------------------------- 0.7/16.1 MB 5.0 MB/s eta 0:00:04
   -- ------------------------------------- 0.9/16.1 MB 4.7 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/16.1 MB 4.1 MB/s eta 0:00:04
   --- ------------------------------------ 1.2/16.1 MB 4.1 MB/s eta 0:00:04
   --- ------------------------------------ 1.4/16.1 MB 4.3 MB/s eta 0:00:04
   ---- ----------------------------------- 1.7/16.1 MB 4.5 MB/s eta 0:00:04
   ---- ----------------------------------- 1.8/16.1 MB 4.2 MB/s eta 0:00:04
   ----- ---------------------------------- 2.1/16.1 MB 4.5 MB/s eta 0:00:04
   ----- ---------------------------------- 2.3/16.1 MB 4.2 MB/s eta 0:00:04
   ------ --------------------------------- 2.6/16.1 MB 4.5 MB/s eta 0:00:03
   ------ --------------------------------- 2.7/16.1 MB 4.4 MB/s eta 0:00:04
   ------- -------------------------------- 2.9/16.1 MB 4.3 MB/s eta 0:00:04
   ------- -------------------------------- 3.1/16.1 MB 4.4 MB/s eta 0:00:03
   -------- ------------------------------- 3.2/16.1 MB 4.2 MB/s eta 0:00:04
   -------- ------------------------------- 3.5/16.1 MB 4.4 MB/s eta 0:00:03
   -------- ------------------------------- 3.6/16.1 MB 4.2 MB/s eta 0:00:03
   --------- ------------------------------ 3.9/16.1 MB 4.3 MB/s eta 0:00:03
   ---------- ----------------------------- 4.2/16.1 MB 4.4 MB/s eta 0:00:03
   ---------- ----------------------------- 4.2/16.1 MB 4.4 MB/s eta 0:00:03
   ---------- ----------------------------- 4.2/16.1 MB 4.4 MB/s eta 0:00:03
   ---------- ----------------------------- 4.2/16.1 MB 4.4 MB/s eta 0:00:03
   ---------- ----------------------------- 4.2/16.1 MB 4.4 MB/s eta 0:00:03
   ---------- ----------------------------- 4.2/16.1 MB 3.6 MB/s eta 0:00:04
   ---------- ----------------------------- 4.2/16.1 MB 3.6 MB/s eta 0:00:04
   ---------- ----------------------------- 4.3/16.1 MB 3.4 MB/s eta 0:00:04
   ---------- ----------------------------- 4.3/16.1 MB 3.4 MB/s eta 0:00:04
   ----------- ---------------------------- 4.5/16.1 MB 3.3 MB/s eta 0:00:04
   ----------- ---------------------------- 4.5/16.1 MB 3.2 MB/s eta 0:00:04
   ----------- ---------------------------- 4.6/16.1 MB 3.1 MB/s eta 0:00:04
   ------------ --------------------------- 4.9/16.1 MB 3.2 MB/s eta 0:00:04
   ------------ --------------------------- 4.9/16.1 MB 3.2 MB/s eta 0:00:04
   ------------ --------------------------- 5.2/16.1 MB 3.2 MB/s eta 0:00:04
   ------------- -------------------------- 5.4/16.1 MB 3.3 MB/s eta 0:00:04
   -------------- ------------------------- 5.7/16.1 MB 3.3 MB/s eta 0:00:04
   -------------- ------------------------- 6.0/16.1 MB 3.4 MB/s eta 0:00:03
   --------------- ------------------------ 6.3/16.1 MB 3.5 MB/s eta 0:00:03
   --------------- ------------------------ 6.3/16.1 MB 3.5 MB/s eta 0:00:03
   --------------- ------------------------ 6.3/16.1 MB 3.5 MB/s eta 0:00:03
   --------------- ------------------------ 6.3/16.1 MB 3.5 MB/s eta 0:00:03
   --------------- ------------------------ 6.3/16.1 MB 3.5 MB/s eta 0:00:03
   --------------- ------------------------ 6.3/16.1 MB 3.5 MB/s eta 0:00:03
   --------------- ------------------------ 6.3/16.1 MB 3.0 MB/s eta 0:00:04
   --------------- ------------------------ 6.3/16.1 MB 3.0 MB/s eta 0:00:04
   --------------- ------------------------ 6.3/16.1 MB 3.0 MB/s eta 0:00:04
   --------------- ------------------------ 6.3/16.1 MB 3.0 MB/s eta 0:00:04
   --------------- ------------------------ 6.4/16.1 MB 2.8 MB/s eta 0:00:04
   ---------------- ----------------------- 6.5/16.1 MB 2.8 MB/s eta 0:00:04
   ---------------- ----------------------- 6.5/16.1 MB 2.8 MB/s eta 0:00:04
   ---------------- ----------------------- 6.5/16.1 MB 2.8 MB/s eta 0:00:04
   ---------------- ----------------------- 6.5/16.1 MB 2.8 MB/s eta 0:00:04
   ---------------- ----------------------- 6.5/16.1 MB 2.6 MB/s eta 0:00:04
   ---------------- ----------------------- 6.5/16.1 MB 2.6 MB/s eta 0:00:04
   ---------------- ----------------------- 6.5/16.1 MB 2.6 MB/s eta 0:00:04
   ---------------- ----------------------- 6.5/16.1 MB 2.6 MB/s eta 0:00:04
   ---------------- ----------------------- 6.6/16.1 MB 2.4 MB/s eta 0:00:04
   ---------------- ----------------------- 6.6/16.1 MB 2.4 MB/s eta 0:00:04
   ---------------- ----------------------- 6.6/16.1 MB 2.4 MB/s eta 0:00:05
   ---------------- ----------------------- 6.7/16.1 MB 2.4 MB/s eta 0:00:05
   ---------------- ----------------------- 6.7/16.1 MB 2.4 MB/s eta 0:00:05
   ---------------- ----------------------- 6.7/16.1 MB 2.4 MB/s eta 0:00:05
   ---------------- ----------------------- 6.7/16.1 MB 2.4 MB/s eta 0:00:05
   ---------------- ----------------------- 6.7/16.1 MB 2.4 MB/s eta 0:00:05
   ---------------- ----------------------- 6.7/16.1 MB 2.2 MB/s eta 0:00:05
   ---------------- ----------------------- 6.7/16.1 MB 2.2 MB/s eta 0:00:05
   ---------------- ----------------------- 6.8/16.1 MB 2.1 MB/s eta 0:00:05
   ---------------- ----------------------- 6.8/16.1 MB 2.1 MB/s eta 0:00:05
   ----------------- ---------------------- 6.9/16.1 MB 2.1 MB/s eta 0:00:05
   ----------------- ---------------------- 6.9/16.1 MB 2.1 MB/s eta 0:00:05
   ----------------- ---------------------- 7.0/16.1 MB 2.1 MB/s eta 0:00:05
   ----------------- ---------------------- 7.1/16.1 MB 2.1 MB/s eta 0:00:05
   ------------------ --------------------- 7.3/16.1 MB 2.1 MB/s eta 0:00:05
   ------------------ --------------------- 7.3/16.1 MB 2.1 MB/s eta 0:00:05
   ------------------ --------------------- 7.4/16.1 MB 2.1 MB/s eta 0:00:05
   ------------------ --------------------- 7.5/16.1 MB 2.1 MB/s eta 0:00:05
   ------------------- -------------------- 7.6/16.1 MB 2.1 MB/s eta 0:00:05
   ------------------- -------------------- 7.8/16.1 MB 2.1 MB/s eta 0:00:04
   ------------------- -------------------- 8.0/16.1 MB 2.1 MB/s eta 0:00:04
   -------------------- ------------------- 8.1/16.1 MB 2.1 MB/s eta 0:00:04
   -------------------- ------------------- 8.3/16.1 MB 2.1 MB/s eta 0:00:04
   -------------------- ------------------- 8.4/16.1 MB 2.1 MB/s eta 0:00:04
   --------------------- ------------------ 8.6/16.1 MB 2.2 MB/s eta 0:00:04
   --------------------- ------------------ 8.8/16.1 MB 2.2 MB/s eta 0:00:04
   ---------------------- ----------------- 8.9/16.1 MB 2.2 MB/s eta 0:00:04
   ---------------------- ----------------- 9.1/16.1 MB 2.2 MB/s eta 0:00:04
   ---------------------- ----------------- 9.2/16.1 MB 2.2 MB/s eta 0:00:04
   ----------------------- ---------------- 9.4/16.1 MB 2.2 MB/s eta 0:00:03
   ----------------------- ---------------- 9.5/16.1 MB 2.2 MB/s eta 0:00:03
   ------------------------ --------------- 9.7/16.1 MB 2.3 MB/s eta 0:00:03
   ------------------------ --------------- 9.8/16.1 MB 2.3 MB/s eta 0:00:03
   ------------------------ --------------- 10.0/16.1 MB 2.3 MB/s eta 0:00:03
   ------------------------ --------------- 10.0/16.1 MB 2.3 MB/s eta 0:00:03
   ------------------------- -------------- 10.2/16.1 MB 2.3 MB/s eta 0:00:03
   ------------------------- -------------- 10.4/16.1 MB 2.3 MB/s eta 0:00:03
   -------------------------- ------------- 10.6/16.1 MB 2.3 MB/s eta 0:00:03
   -------------------------- ------------- 10.8/16.1 MB 2.3 MB/s eta 0:00:03
   --------------------------- ------------ 11.0/16.1 MB 2.3 MB/s eta 0:00:03
   --------------------------- ------------ 11.1/16.1 MB 2.3 MB/s eta 0:00:03
   --------------------------- ------------ 11.2/16.1 MB 2.3 MB/s eta 0:00:03
   ---------------------------- ----------- 11.4/16.1 MB 2.3 MB/s eta 0:00:03
   ---------------------------- ----------- 11.5/16.1 MB 2.2 MB/s eta 0:00:03
   ---------------------------- ----------- 11.5/16.1 MB 2.2 MB/s eta 0:00:03
   ---------------------------- ----------- 11.5/16.1 MB 2.2 MB/s eta 0:00:03
   ---------------------------- ----------- 11.5/16.1 MB 2.2 MB/s eta 0:00:03
   ---------------------------- ----------- 11.5/16.1 MB 2.2 MB/s eta 0:00:03
   ---------------------------- ----------- 11.5/16.1 MB 2.2 MB/s eta 0:00:03
   ---------------------------- ----------- 11.5/16.1 MB 2.2 MB/s eta 0:00:03
   ----------------------------- ---------- 11.8/16.1 MB 2.1 MB/s eta 0:00:03
   ----------------------------- ---------- 12.0/16.1 MB 2.1 MB/s eta 0:00:02
   ------------------------------ --------- 12.4/16.1 MB 2.1 MB/s eta 0:00:02
   ------------------------------- -------- 12.5/16.1 MB 2.1 MB/s eta 0:00:02
   ------------------------------- -------- 12.9/16.1 MB 2.1 MB/s eta 0:00:02
   -------------------------------- ------- 13.0/16.1 MB 2.2 MB/s eta 0:00:02
   -------------------------------- ------- 13.2/16.1 MB 2.1 MB/s eta 0:00:02
   --------------------------------- ------ 13.4/16.1 MB 2.1 MB/s eta 0:00:02
   --------------------------------- ------ 13.7/16.1 MB 2.1 MB/s eta 0:00:02
   ---------------------------------- ----- 14.0/16.1 MB 2.2 MB/s eta 0:00:01
   ----------------------------------- ---- 14.3/16.1 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 14.6/16.1 MB 2.4 MB/s eta 0:00:01
   ------------------------------------- -- 15.0/16.1 MB 2.4 MB/s eta 0:00:01
   ------------------------------------- -- 15.2/16.1 MB 2.4 MB/s eta 0:00:01
   -------------------------------------- - 15.3/16.1 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  15.7/16.1 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  15.9/16.1 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  16.0/16.1 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  16.1/16.1 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 16.1/16.1 MB 2.4 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.2.0

In [71]:
from sqlalchemy import create_engine
import mysql.connector

In [72]:
mysql+mysqlconnector://<username>:<password>@<host>/<database>

SyntaxError: invalid syntax (877334819.py, line 1)

In [76]:
username = 'root'
password = 'root'
host = '127.0.0.1'  # 'localhost' or IP address
database = 'retailorder'

# Create the engine
engine = create_engine(f'mysql+mysqlconnector://{username}:{password}@{host}/{database}')

In [78]:
df.to_sql('df_orders',con=engine ,index=False ,if_exists='append')

9994

In [79]:
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'quantity', 'discount', 'sales_price', 'profit'],
      dtype='object')

In [82]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sales_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8